### ISSUE TITLE
All necessary steps to have the task services up and running in order to integrate with the webapp

### ISSUE THREAD

**Issue by rsanchej** [hres/cfg-task-service#1]
Please follow the steps listed out in hres/cfg-task-service/README.md to manually build and manually deploy the task services in order to have them up and running to integrate to the classification webapp.

**Comment by weifang993** [comment]
Please remove me  from this github.  I no longer work for HC.

**Comment by rsanchej** [comment]
cfg-task-service is failing to connect to postgresql database.  Can this be taken care of in order to get the application(s) up and running?

**Comment by rsanchej** [comment]
The stack trace tells me that in line 1111 the NullPointerException is because the Conn object was not created by that point.  Running the test is exactly the same only that I am handling the exception.

root cause

java.lang.NullPointerException
	ca.gc.ip346.classification.resource.FoodsResource.doSearchCriteria(FoodsResource.java:1111)
	ca.gc.ip346.classification.resource.FoodsResource.getFoodList(FoodsResource.java:102)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

**Comment by ayoung8** [comment]
Readme only contains steps to install Mongo (not required) but nothing on how to load the schema

**Comment by ayoung8** [comment]
Config should all be good now. But will require adjustment in the source to make the postgres connection via SSL

**Comment by rsanchej** [comment]
README.md has new instructions for updating postgres schema and inserting data.  These need to be manually installed and the scheduled build/deploy will confirm that the update did go through.  It is a new table so the dropping and re-creation of the database is not necessary.
