### ISSUE TITLE
relation "canada_food_group" dos not exist error messgae

### ISSUE THREAD

**Issue by shussain** [hres/cfg-task-service#11]
In catalina.out for cfg-task-servcice's QA branch, has the following error message:

```
11:42:55.059 [http-nio-8080-exec-7] DEBUG ca.gc.ip346.classification.resource.FoodsResource - ERROR: relation "canada_food_group" does not exist
  Position: 62
```
This is when visiting: https://java-dev.hres.ca/cfg-task-service/service/datasets/status

**Comment by rsanchej** [comment]
That's is OK.  I purposely put this DEBUG statement.  It is not an error.  Likewise, if it does not find `canada_food_guide_food_item table` it will still proceed.  That's why there is not `count` in the output.

**Comment by rsanchej** [comment]
Can you force a build/deploy on QA?  I've tried to do it through git commits but it still returns with:

"PostgreSQL database connectivity test: failed - service unavailable"
