### ISSUE TITLE
Disable DDL/DML at build/deploy

### ISSUE THREAD

**Issue by rsanchej** [hres/cfg-task-service#14]
@ayoung8 I have added a boolean property to `db.properties.template` in order to decide whether or
not to drop the database and re-create a new one every time the project gets
built/deployed.  Should improve productivity. Thanks

**Comment by ayoung8** [comment]
there's a trigger script that allows you to drop via the ras server so this way you don't need to incorporate into the code and have different bits between dev/test/prod
check with romario he has access to the script.
please close ticket if no longer required.

**Comment by rsanchej** [comment]
I forgot to mention that this has to do with Jenkins Continuous Integration on cfg-task-service.  Every time I make Java changes/commits to github the CI gets triggered.  My understanding is that the way this CI is set up is that the DB gets dropped every time and re-created via the PSQL file provided plus any other DDL/DML that needs to be done.  From our discussion, the idea is that I provide you with some kind of switch/bit so that when the CI gets triggered and before the DB gets dropped, it checks this switch to determine whether to drop the DB and proceed to run the PSQL or not do neither.  The idea behind this is to improve performance/productivity by disabling the DB operations and only enabling them when necessary.  Not sure what this has to do with the ras server?  346b does not use the ras server at all.

**Comment by ayoung8** [comment]
The db drop from CI has been disabled, the trigger to drop the db is found on the ras server.
