### ISSUE TITLE
Review changes to pom.xml for the QA branch

### ISSUE THREAD

**Issue by shussain** [hres/cfg-task-service#5]
For deploying the cfg-task-service's QA branch, the proper name is needed.

The change is in  commit is 5de99c4 in the QA branch (please note that the commit has been reverted for now). The change is needed in order to be able to deploy cfg-task-service-qa in an automated manner (the alternative is ignoring any future changes to the pom.xml which will make any updates problematic).

**Comment by rsanchej** [comment]
If the change is needed then please go ahead.  The less problematic future changes to pom.xml the better.  Thanks.

**Comment by shussain** [comment]
Thank you. The latest pom.xml in QA branch refers to cfg-task-service-qa.

**Comment by rsanchej** [comment]
cfg-task-service did deploy and it did work as intended.  This morning there are a lot of time outs and java heap space issues.  Can you please take a look at this.  This is new.

**Comment by shussain** [comment]
@rsanchej Created a new issue #6 about that. I have assigned it to Anthony Young since SOP is that he has to be aware of any support issue so that can triage them first

**Comment by rsanchej** [comment]
I just updated QA branch with the latest changes in master.  Can you confirm that the changes you made to the QA branch still persist.  Thanks.

**Comment by shussain** [comment]
Updated and deployed the latest code (https://java-dev.hres.ca/cfg-task-service-qa/). It seems to be working.

Thank you for the headsup

**Comment by rsanchej** [comment]
BTW, I updated:
- cfg-task-service-qa
- cfg-classification-service-qa

**Comment by shussain** [comment]
Deployed both and while the deployment did not fail, the sites are not loadign when I visit them (I am getting timred out. I am guessing that is due to testing of cfg-task-service (#6)

**Comment by rsanchej** [comment]
I just ran DEV and QA.  They are both working.  The timeouts and out-of-memory errors seem to have been resolved on the server-side.  Thanks.

**Comment by shussain** [comment]
Great. Thank you
