### ISSUE TITLE
Naming of DB insances

### ISSUE THREAD

**Issue by shussain** [hres/cfg-task-service#9]
Raul had requested that cfnfadm have PostgreSQL instances named [cnfadm-qa & cnfadm-dev](https://github.com/hres/cfg-task-service/pull/7#issuecomment-331162735)

Similarly the [mongodb instances ](https://github.com/hres/cfg-task-service/pull/7#issuecomment-331183477)have the same convention

**Comment by shussain** [comment]
Raul for the mongodb instances, do you want me to rename the current DB instsance? Or can I safely just drop it and create a new (empty) mongo instance of cnfadm-dev?

**Comment by shussain** [comment]
@rsanchej the PostgreSQL db can't be cnfadm-dev and cnfadm-qa since '-' is not a valid character (https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS)

As such, your choices are no space (so cnfadmdev and cnfadmdqa) or separated with underscore (cnfadm_qa and cnfadm_dev). As such which convention do you prefer?

-----

In addition, what do you want to do with the current mongo DB instance for dev? It contains several rows of data. Shoudl I go ahead and drop it?

**Comment by rsanchej** [comment]
> Raul had requested that cfnfadm have PostgreSQL instances named cnfadm-qa & cnfadm-dev

Please rename the database PostgreSQL instances to `cfg_db_qa` and `cfg_db_dev`

> Raul for the mongodb instances, do you want me to rename the current DB instsance? Or can I safely just drop it and create a new (empty) mongo instance of cnfadm-dev?

For mongodb instances, yes just drop it.  I believe you can just drop them and the first call to them will create them, but rename them exactly the same as the PostgreSQL instances: `cfg_db_qa` and `cfg_db_dev`.  I will make sure the properties have this change.

> @rsanchej the PostgreSQL db can't be cnfadm-dev and cnfadm-qa since '-' is not a valid character (https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS)

> As such, your choices are no space (so cnfadmdev and cnfadmdqa) or separated with underscore (cnfadm_qa and cnfadm_dev). As such which convention do you prefer?

Please rename the database PostgreSQL instances to `cfg_db_qa` and `cfg_db_dev`

> In addition, what do you want to do with the current mongo DB instance for dev? It contains several rows of data. Shoudl I go ahead and drop it?

For mongodb dev instance, yes just drop it.

**Comment by rsanchej** [comment]
Note: currently there are other databases in mongodb, specially one called `rulesets`.  This one needs to stay as is and it will be shared by both `DEV` and `QA` for now.  I might come up with a different design in the future.  So please don't drop the `rulesets` database.  Thanks

**Comment by shussain** [comment]
Raul have made changes to the PostgreSQL DB and MongoDB instances.

**Comment by rsanchej** [comment]
For both PostgreSQL and MongoDb, instances are: `cfg_db_dev` and `cfg_db_qa` (typo corrected)

BTW, `create_table_and_load_data.psql` was created to be used by Jenkins on HRES.  And I understand that connecting to the db is problematic so that statement can be removed (`\c cfg_db_dev`).  This results in one of `create_table_and_load_data.psql` and `HRE_create_table_and_load_data.psql` being redundant.  I'll drop `create_table_and_load_data.psql`

**Comment by shussain** [comment]
>  This results in one of create_table_and_load_data.psql and HRE_create_table_and_load_data.psql being redundant. I'll drop create_table_and_load_data.psql

Noted. Thank you.

@rsanchej Can this issue be closed? Or is there still some outstanding issue?

**Comment by rsanchej** [comment]
@shussain Can you confirm that QA CI does create the postgresql database?  My QA test connects to postgresql but apparently there is no schema.  I think there's a build on its way.

**Comment by rsanchej** [comment]
If the CI for QA did go through, I just confirmed that the schema was not created.  If we are using `HRE_create_table_and_load_data.psql`, can you make sure that Jenkins calls this file and not the previous one?  Thanks

**Comment by shussain** [comment]
@rsanchej I am confused since I can confirm that the schema and data is present for the QA's DB instance.

```
$ psql cfg_db_qa
psql (9.5.8)
Type "help" for help.

cfg_db_qa=# \d canada_food_guide_food_item;
              Table "public.canada_food_guide_food_item"
                 Column                 |       Type       | Modifiers 
----------------------------------------+------------------+-----------
 type                                   | smallint         | 
 code                                   | integer          | not null
 name                                   | text             | 
 cnf_group_code                         | integer          | 
 cfg_code                               | integer          | 
 cfg_code_update_date                   | date             | 
 energy_kcal                            | double precision | 
 sodium_amount_per_100g                 | double precision | 
 sodium_imputation_reference            | text             | 
 sodium_imputation_date                 | date             | 
 sugar_amount_per_100g                  | double precision | 
 sugar_imputation_reference             | text             | 
 sugar_imputation_date                  | date             | 
 transfat_amount_per_100g               | double precision | 
 transfat_imputation_reference          | text             | 
 transfat_imputation_date               | date             | 
 satfat_amount_per_100g                 | double precision | 
 satfat_imputation_reference            | text             | 
 satfat_imputation_date                 | date             | 
 totalfat_amount_per_100g               | double precision | 
 totalfat_imputation_reference          | text             | 
 totalfat_imputation_date               | date             | 
 contains_added_sodium                  | boolean          | 
 contains_added_sodium_update_date      | date             | 
 contains_added_sugar                   | boolean          | 
 contains_added_sugar_update_date       | date             | 
 contains_free_sugars                   | boolean          | 
 contains_free_sugars_update_date       | date             | 
 contains_added_fat                     | boolean          | 
 contains_added_fat_update_date         | date             | 
 contains_added_transfat                | boolean          | 
 contains_added_transfat_update_date    | date             | 
 contains_caffeine                      | boolean          | 
 contains_caffeine_update_date          | date             | 
 contains_sugar_substitutes             | boolean          | 
 contains_sugar_substitutes_update_date | date             | 
 reference_amount_g                     | double precision | 
 reference_amount_measure               | text             | 
 food_guide_serving_g                   | double precision | 
 food_guide_serving_measure             | text             | 
 food_guide_update_date                 | date             | 
 tier_4_serving_g                       | double precision | 
 tier_4_serving_measure                 | text             | 
 tier_4_serving_update_date             | date             | 
 rolled_up                              | boolean          | 
 rolled_up_update_date                  | date             | 
 override_small_ra_adjustment           | boolean          | 
 toddler_item                           | boolean          | 
 replacement_code                       | integer          | 
 commit_date                            | date             | 
 comments                               | text             | 
Indexes:
    "canada_food_guide_food_item_pkey" PRIMARY KEY, btree (code)

cfg_db_qa=# select count(*) from canada_food_guide_food_item;
 count 
-------
  7038
(1 row)
```



How are you confirming that the schema is not being created? What is the missing schema?

**Comment by rsanchej** [comment]
Make a call to:

https://java-dev.hres.ca/cfg-task-service-qa/service/datasets/status

This call writes DEBUG statements to catalina.out that tell you that `canada_food_guide_food_item` does not exists.

It would be great if these logs were available online as they once were.  What happened?

https://java-dev.hres.ca/cfg-task-service/service/datasets/status

gives you the count at the bottom

**Comment by rsanchej** [comment]
Is `db.properties.template` hence `db.properties` in both `DEV` and `QA` identical except for the database name: `cfg_db_dev` and `cfg_qa_qa`?

**Comment by rsanchej** [comment]
I meant `host`, `port`, ... all the same?

**Comment by shussain** [comment]
@rsanchej  I think I have figured out the issue. The user cfgadmqauser (which has access to cfg_db_qa) does *not* get granted ownership to the canada_fodo_guide_item [here](https://github.com/hres/cfg-task-service/blob/6c8736cb259787678ae14f5ae31c73262c541985/src/scripts/sql/create_canada_food_guide_food_item.sql#L56).

As you will note this is in the QA branch. 

While there are different solutions, I would request you modify that line to use cnfadmqaqauser. That way, we have seperate users for the DB instances. Once that chagne is done, i suspect the issue you have encountered will go away

**Comment by rsanchej** [comment]
These are the contents of `db.properties.template` for DEV:
````
# PostgreSQL DB properties
jdbc.driver=org.postgresql.Driver
jdbc.url=jdbc:postgresql://localhost:5432/cfg_db_dev?sslmode=require
jdbc.username=root
jdbc.password=password
````
What I understand/guess is that Jenkins replaces `root` with `cnfadmuser` at build-time.

So, in a similar fashion, `db.properties.template` for QA:
````
# PostgreSQL DB properties
jdbc.driver=org.postgresql.Driver
jdbc.url=jdbc:postgresql://localhost:5432/cfg_db_qa?sslmode=require
jdbc.username=root
jdbc.password=password
````
Jenkins will replace `root` with `cfgadmqauser`.  I have no access to that script.

**Comment by rsanchej** [comment]
Sorry:

Jenkins will replace `root` with `cnfadmqauser` at build-time.

Thanks

**Comment by shussain** [comment]
@rsanchej Understand.

There is a change I will require from you. I have made a [pull request](https://github.com/hres/cfg-task-service/pull/10) for it.

**Comment by shussain** [comment]
@rsanchej I saw "PostgreSQL database connectivity test: failed - service unavailable" error message and I have it fixed

**Comment by rsanchej** [comment]
So QA is working!
However, DEV is now broken! but I think I've pointed out the problem.  It looks like Jenkins is not changing the properties files for connecting to the cfg-task-services.  The resulting message looks like a CORS error saying that https://lam-dev.hres.ca/..... was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:8080/cfg-task-service/service/datasets?env=prod' .... 

localhost:8080 is what got my attention reflecting what is the the properties files and this should be java-dev.hres.ca .....

Makes sense?

**Comment by rsanchej** [comment]
I confirmed the PostgreSQL fix.  Thanks

**Comment by shussain** [comment]
Good to hear about working PostgreSQL.

In regards to the error you are getting, the only issue I can think of is that it is a configuration. I note that the following use host. 
```
src/main/java/ca/gc/ip346/util/mongodb.properties:2:host=mongo-dev.hc.local
src/main/java/ca/gc/ip346/util/requestUri.properties:2:host=http://localhost
src/main/java/ca/gc/ip346/util/db.properties.template:3:jdbc.url=jdbc:postgresql://localhost:5432/cfg_db_dev?sslmode=require
```

As you can see, requestUri is using localhost. And it is using port 8080. 

I am assuming I should change it to 443 for cfg-task-service & cfg-task-service-qa? Is that the case? 

If so, can you please update the README documentation?

**Comment by rsanchej** [comment]
Sorry about the confusion but it appears that this last issue is on the client, so we are looking at fixing it right know. 

cfg-classification-webapp is CI, right?  So we should see the fix soon. 

cfg-classification-webapp-qa is CI too?

Thanks

**Comment by shussain** [comment]
> cfg-classification-webapp is CI, right? So we should see the fix soon.
> cfg-classification-webapp-qa is CI too?


Yes, both of them are CI.   

-------------

Since the original issue has been fixed, I am going to close this ticket. If you have other issues (e.g. CI is not working, further errors), please create new github issue in the relevant repo and assign it to @ayoung8 to triage and assess.

**Comment by shussain** [comment]
Thank you for your help @rsanchej    I really appreciate your assistance

**Comment by rsanchej** [comment]
Thank you

**Comment by rsanchej** [comment]
Looks like QA is working!  DEV is crashing when trying to save a newly created dataset.  It throws a 500 Internal Server Error.  Unfortunately, I don't have access to the logs specially `catalina.out` off `Tomcat`, but I was able to re-create the error and Mongo complains about trying to recreate a database that exists with a different casing---see the attached screen shot.
Can you see that DEV also follows the same naming convention: `cfg_db_dev`
Thanks

![wrongname](https://user-images.githubusercontent.com/24256238/30809034-56b0f608-a1ce-11e7-9650-5f752170d4fe.png)

**Comment by shussain** [comment]
@rsanchej I have made the change to the mongo DB name. The changes have been deployed to java-dev.hres.ca

Please give it 5 minutes and test again.

**Comment by rsanchej** [comment]
@shussain DEV is working now.  Thanks
